import React from "react";
import { cn } from "../lib/cn";

const LOGO_SRC = `${process.env.PUBLIC_URL || ""}/expal-logo.png`;

/**
 * App branding image from public/expal-logo.png (generated by npm run logo:apply).
 */
export default function AppLogo({ size = 36, showText = false, className }) {
  return (
    <span className={cn("flex items-center gap-2 shrink-0", className)}>
      <img
        src={LOGO_SRC}
        alt="EXPal"
        width={size}
        height={size}
        className="rounded-xl object-cover bg-card ring-1 ring-border"
        style={{ width: size, height: size }}
      />
      {showText ? (
        <span className="font-semibold text-foreground hidden sm:inline">EXPal</span>
      ) : null}
    </span>
  );
}
